virtual_machines:

  windows:
    socket: /home/user/vm/windows/qmp-sock
    delay: 1
    hubs:
      - xhci0.0
      - xhci1.0
    ports:
      - /devices/pci0000:00/0000:00:14.0/usb3/3-3
      - /devices/pci0000:00/0000:00:14.0/usb3/3-4
